### ISSUE TITLE
Bug introduced with the addition of the euro sign

### ISSUE THREAD

**Issue by neumannjan** [michalkahle/czech-coder-xkb#7]
Try writing with caps lock on, while holding Alt Gr. The e key ignores the caps lock.

**Comment by michalkahle** [comment]
Hi, I normally never use caps lock and have it switched off but now I tested and it seems to work as expected for me: when caps lock is on and Alt Gr is pressed the "e" key produces capital "E". Together with shift it produces "€". I'm running Ubuntu 16.4. What is your observation? You see lower case "e" in this situation?

**Comment by neumannjan** [comment]
Yes, I get a lowercase "e". I'm on Fedora 28, gnome shell. I have little experience with this, therefore I don't know if there are any logs that you may find useful.

**Comment by michalkahle** [comment]
Could you please make sure you have installed the last commit and activated it? Just `git pull`, run the `install.sh` and then `setxkbmap -layout cz -variant cz_programmer`. If the problem persists please create a source file of your current configuration by running `xkbcomp -xkb $DISPLAY xkbmap` and send me the resulting `xkbmap` file.

**Comment by michalkahle** [comment]
In case you wanted to hack a bit and try to find the solution yourself [An Unreliable Guide to XKB Configuration](https://www.charvolant.org/doug/xkb/html/xkb.html) is the best resource on xkb I know of.

**Comment by neumannjan** [comment]
The problem does persist (I was already at the newest commit). The `kxbmap` file is attached below:

[xkbmap.txt](https://github.com/michalkahle/czech-programmer-keyboard-layout-xkb/files/1977417/xkbmap.txt)

**Comment by michalkahle** [comment]
I can confirm to see the behavior you describe but the structure of your xkb file is quite different than what I'm used to in Debian and I don't know how to fix it right now. For the time being you can try to use this xkb map:

[cz_programmer.txt](https://github.com/michalkahle/czech-programmer-keyboard-layout-xkb/files/1987449/cz_programmer.txt)

To set it, use `xkbcomp cz_programmer.txt $DISPLAY`

**Comment by michalkahle** [comment]
Maybe even better: install GNOME Tweak Tool and in section 'Typing' and 'Caps Lock key behavior' select 'Caps Lock uses internal capitalization; Shift "pauses" Caps Lock'.

**Comment by neumannjan** [comment]
Internal capitalization did the trick. I have no idea why, but thank you.

**Comment by michalkahle** [comment]
You are welcome. :) Enjoy and spread the word. ;)
