### ISSUE TITLE
Missing sudo in documentation

### ISSUE THREAD

**Issue by davidvavra** [michalkahle/czech-coder-xkb#8]
Wow, this was the easiest setup how to get Czech Programmers for Ubuntu!

There is one sudo missing in documentation, it should be:

`sudo curl https://raw.githubusercontent.com/michalkahle/czech-coder-xkb-keyboard-layout/master/cz-coder-xkb.patch | sudo patch -bp`

**Comment by michalkahle** [comment]
Great! Thanks for pointing this out. :)
