### ISSUE TITLE
kb-data/focal,focal,now 2.29-2 all [installed,automatic]

### ISSUE THREAD

**Issue by redy007** [michalkahle/czech-coder-xkb#9]
Does the latest patch  works for the Ubuntu 20.04 lts too? Thank you for you answer.

**Comment by michalkahle** [comment]
I have checked the `xkb-data` in Ubuntu 20.4 and the "coder" variant is already there, no need to patch. Try to activate it by `setxkbmap -layout cz -variant coder` and please report how it went.

**Comment by schubertjan** [comment]
`setxkbmap -layout cz -variant coder` works fine for me on Ubuntu 20.04

**Comment by michalkahle** [comment]
Great. Closing this issue.
